version: '2'
services:
    oncatalog-app:
        image: oncatalog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://oncatalog-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=OnCatalog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://oncatalog-elasticsearch:9200
        ports:
            - 8080:8080
    oncatalog-mongodb:
        extends:
            file: mongodb.yml
            service: oncatalog-mongodb
    oncatalog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: oncatalog-elasticsearch
